# Generated by Django 5.2.5 on 2025-09-01 09:17

import netbox_ddns.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_ddns', '0013_reversezone_created_reversezone_custom_field_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extradnsname',
            name='name',
            field=models.CharField(max_length=255, validators=[netbox_ddns.validators.DNSNameValidator()]),
        ),
    ]
