# Generated by Django 5.2.6 on 2025-10-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_ddns', '0014_alter_extradnsname_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='protocol',
            field=models.CharField(default='udp', max_length=3),
        ),
    ]
